export const usersList = [
    {
        name: "User One",
        password: "abc123",
        walletAmount: 1000,
    },
]

export const instockProducts = [
    {
        img: "/assets/images/black-watch.png",
        name: "DM 9106",
        price: 100,
        instockQuantity: 10,
        quantity: 1,
        category: "watch",
    },
    {
        img: "/assets/images/blue-watch.png",
        name: "DM 7405",
        price: 110,
        instockQuantity: 10,
        quantity: 1,
        category: "watch",
    },
    {
        img: "/assets/images/silver-watch.png",
        name: "DM 9421",
        price: 120,
        instockQuantity: 10,
        quantity: 1,
        category: "watch",
    },
    {
        img: "/assets/images/gold-watch.png",
        name: "DM 9999",
        price: 130,
        instockQuantity: 10,
        quantity: 1,
        category: "watch",
    },
    {
        img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
        name: "Nike White",
        price: 140,
        instockQuantity: 10,
        quantity: 1,
        category: "sneaker",
    },
    {
        img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
        name: "Nike Black",
        price: 100,
        instockQuantity: 10,
        quantity: 1,
        category: "sneaker",
    },
    {
        img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
        name: "Nike Cyan",
        price: 120,
        instockQuantity: 10,
        quantity: 1,
        category: "sneaker",
    },
    {
        img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
        name: "Nike Red",
        price: 100,
        instockQuantity: 10,
        quantity: 1,
        category: "sneaker",
    },
    {
        img: "/assets/images/silver2-watch.png",
        name: "DM 7505",
        price: 110,
        instockQuantity: 10,
        quantity: 1,
        category: "watch",
    },
    {
        img: "/assets/images/copper-watch.png",
        name: "DM 9989",
        price: 100,
        instockQuantity: 10,
        quantity: 1,
        category: "watch",
    },
    {
        img: "/assets/images/blue2-watch.png",
        name: "DM 7300",
        price: 130,
        instockQuantity: 10,
        quantity: 1,
        category: "watch",
    },
    {
        img: "/assets/images/silver3-watch.png",
        name: "DM 9976",
        price: 120,
        instockQuantity: 10,
        quantity: 1,
        category: "watch",
    },
    {
        img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
        name: "Puma Black",
        price: 140,
        instockQuantity: 10,
        quantity: 1,
        category: "sneaker",
    },
    {
        img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
        name: "Puma White",
        price: 150,
        instockQuantity: 10,
        quantity: 1,
        category: "sneaker",
    },
    {
        img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
        name: "Puma Gray",
        price: 150,
        instockQuantity: 10,
        quantity: 1,
        category: "sneaker",
    },
    {
        img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
        name: "Puma Red",
        price: 100,
        instockQuantity: 10,
        quantity: 1,
        category: "sneaker",
    },
]

export const cartProducts = []

export const boughtHistoryProducts = []